// Names, spellings and display formats of units, currencies, word-operators
// and date words (en + ru). Conversion ratios live in unitdata.ts.
import type { VocabLocale } from "./vocab";

export const EN: VocabLocale = {
  "Angle": {
    "degree.format": "°",
    "degree.variants": "degree,°,degrees,arcdegree",
    "radian.format": "rad",
    "radian.variants": "radian,rad,radians"
  },
  "Area": {
    "acre.format": "acre",
    "acre.variants": "acre,acres",
    "are.format": "a",
    "are.variants": "a,are,ares",
    "area.format": "%@²",
    "area.templates": "square %@,sq %@,sq%@,%@²,%@ ²,%@ 2",
    "hectare.format": "ha",
    "hectare.variants": "hectare,hectares,ha",
    "ping.format": "píng",
    "ping.variants": "ping,píng,pings,píngs"
  },
  "Css": {
    "em.format": "em",
    "em.variants": "em,ems",
    "pixel.format": "px",
    "pixel.variants": "pixel,pixels,px,px."
  },
  "Currency": {
    "AED.format": "%@ Dh",
    "AED.variants": "United Arab Emirates dirham,Dirham,Dirhams,UAE Dirham,UAE Dirhams,Dhs,د.إ",
    "AFN.format": "%@ Af",
    "AFN.variants": "Afgani,Afgan Afgani,Afs,؋,Af",
    "ALL.format": "%@ L",
    "ALL.variants": "Lek,Albanian Lek,Albanian Leks",
    "AMD.format": "%@ Դ",
    "AMD.variants": "Armenian Dram,Dram,Drams,Armenian Drams,Դ",
    "ANG.format": "ƒ %@",
    "ANG.variants": "Netherlands Antillean Guilders,Netherlands Antillean Guilder,Guilder,Guilders,NAƒ,NAf,ƒ",
    "AOA.format": "%@ Kz",
    "AOA.variants": "Angolan Kwanzas,Angolan Kwanza,Kwanza,Kwanzas,Kz",
    "ARS.format": "%@ ARS",
    "ARS.variants": "Argentine Peso,Argentine Pesos",
    "AUD.format": "$%@ AUD",
    "AUD.variants": "Australian Dollars,Australian Dollar",
    "AWG.format": "%@ Afl.",
    "AWG.variants": "Aruban florin,florin,Afl.",
    "AZN.format": "%@ man.",
    "AZN.variants": "Azerbaijani Manats,Azerbaijani Manat,Manat,Manats,man.",
    "BAM.format": "%@ KM",
    "BAM.variants": "Bosnia and Herzegovina convertible mark,Bosnia and Herzegovina convertible marks,convertible mark,convertible marks,Maraka",
    "BBD.format": "%@ BBD",
    "BBD.variants": "Barbados Dollars,Barbados Dollar",
    "BDT.format": "%@ Tk",
    "BDT.variants": "Bangladeshi Takas,Bangladeshi Taka,Takas,Taka,Tk,৳",
    "BGN.format": "%@ лв.",
    "BGN.variants": "Bulgarian Levs,Bulgarian Lev,Lev,Leva,Bulgarian Leva,лв.",
    "BHD.format": "%@ BD",
    "BHD.variants": "Bahraini Dinars,Bahraini Dinar,.د.ب,BD",
    "BIF.format": "%@ FBu",
    "BIF.variants": "Burundi Francs,Burundi Franc,Burundian franc,Burundian francs,FBu",
    "BMD.format": "$ %@",
    "BMD.variants": "Bermudian Dollars,Bermudian Dollar,BD$",
    "BND.format": "B$ %@",
    "BND.variants": "Brunei Dollars,Brunei Dollar",
    "BOB.format": "Bs %@",
    "BOB.variants": "Bolivian Bolivianos,Bolivian Boliviano,Bolivianos,Boliviano,Bs",
    "BRL.format": "R$ %@",
    "BRL.variants": "Brazilian Reals,Brazilian Real,R$",
    "BSD.format": "B$ %@",
    "BSD.variants": "Bahamian Dollars,Bahamian Dollar",
    "BTC.format": "%@ B⃦",
    "BTC.variants": "Bitcoins,Bitcoin,B⃦,xbt",
    "BTN.format": "Nu. %@",
    "BTN.variants": "Bhutanese Ngultrum,Ngultrum,Bhutanese Ngultrums,Ngultrums,Nu.",
    "BWP.format": "%@ BWP",
    "BWP.variants": "Botswana Pula,Pula",
    "BYN.format": "%@ BYN",
    "BYN.variants": "Belarusian ruble,Belarusian rubles,bel. ruble,bel rubles",
    "BYR.format": "%@ BYR",
    "BYR.variants": "BYR",
    "BZD.format": "BZ$ %@",
    "BZD.variants": "Belize Dollars,Belize Dollar,BZ$",
    "CAD.format": "$%@ CAD",
    "CAD.variants": "Canadian Dollars,Canadian Dollar,CA$,$ CAD,$CAD",
    "CDF.format": "%@ FC",
    "CDF.variants": "Congolese Francs,Congolese Franc,FC",
    "CHF.format": "%@ SFr.",
    "CHF.variants": "Swiss Francs,Swiss Franc,SFr.",
    "CLP.format": "%@ CLP",
    "CLP.variants": "Chilean Pesos,Chilean Peso",
    "CNY.format": "%@ ¥",
    "CNY.variants": "Chinese Yuans,Chinese Yuan,yuan,yuans,元,RMB",
    "COP.format": "$%@ COP",
    "COP.variants": "Colombian Pesos,Colombian Peso",
    "CRC.format": "%@ ₡",
    "CRC.variants": "Costa Rican Colones,Costa Rican Colon,Colon,Colones",
    "CUP.format": "$MN %@",
    "CUP.variants": "Cuban Pesos,Cuban Peso,$MN",
    "CVE.format": "%@ CVE",
    "CVE.variants": "Cape Verdean Escudos,Cape Verdean Escudo,Escudos,Escudo,Esc",
    "CZK.format": "%@ Kč",
    "CZK.variants": "Czech Korunas,Czech Koruna,Kč",
    "DJF.format": "%@ Fdj",
    "DJF.variants": "Djibouti Francs,Djibouti Franc,Djiboutian Francs,Djiboutian Franc,Fdj",
    "DKK.format": "%@ kr.",
    "DKK.variants": "Danish Kroner,Danish Krone,kr.",
    "DOP.format": "RD$ %@",
    "DOP.variants": "Dominican Pesos,Dominican Peso,RD$",
    "DZD.format": "%@ DA",
    "DZD.variants": "Algerian Dinars,Algerian Dinar,دج",
    "EGP.format": "£%@ EGP",
    "EGP.variants": "Egyptian Pounds,Egyptian Pound",
    "ERN.format": "%@ Nfk",
    "ERN.variants": "Eritrean nakfa,Nakfa,Nfk",
    "ETB.format": "%@ Br",
    "ETB.variants": "Ethiopian Birr,Birr",
    "EUR.format": "€ %@",
    "EUR.variants": "Euro,€",
    "FJD.format": "FJ$ %@",
    "FJD.variants": "Fiji Dollars,Fiji Dollar,Fijian Dollars,Fijian Dollar,FJ$",
    "FKP.format": "£ %@",
    "FKP.variants": "Falkland Islands Pounds,Falkland Islands Pound,Falkland Pounds",
    "GBP.format": "£ %@",
    "GBP.variants": "Pound sterling,Pounds sterling,£,￡,british pound,british pounds,sterling,sterlings,quid,quids",
    "GEL.format": "%@ lari",
    "GEL.variants": "Lari,Georgian Lari",
    "GHS.format": "GH₵ %@",
    "GHS.variants": "Ghana Cedi,Cedi,GH₵",
    "GIP.format": "%@ GIP",
    "GIP.variants": "Gibraltar Pounds,Gibraltar Pound",
    "GMD.format": "%@ D",
    "GMD.variants": "Gambian Dalasi,Dalasi,Gambian Dalasis,Dalasis",
    "GNF.format": "%@ FG",
    "GNF.variants": "Guinean franc,Guinean francs",
    "GTQ.format": "%@ Q",
    "GTQ.variants": "Guatemalan Quetzales,Guatemalan quetzal,Quetzal,Quetzales",
    "GYD.format": "G$ %@",
    "GYD.variants": "Guyanese dollar,Guyanese dollars,G$",
    "HKD.format": "HK$ %@",
    "HKD.variants": "Hong Kong Dollar,Hong Kong Dollars,HK$",
    "HNL.format": "L %@",
    "HNL.variants": "Honduran Lempira,Honduran Lempiras,Lempira,Lempiras",
    "HRK.format": "%@ Kn",
    "HRK.variants": "Croatian Kuna,Kuna",
    "HTG.format": "%@ G",
    "HTG.variants": "Haitian Gourdes,Haitian Gourde,Gourdes,Gourde",
    "HUF.format": "%@ Ft",
    "HUF.variants": "Hungarian Forint,Forint",
    "IDR.format": "Rp %@",
    "IDR.variants": "Indonesian Rupiah,Rp",
    "ILS.format": "%@ NIS",
    "ILS.variants": "Israeli new shekel,new shekalim,new sheqalim,₪,NIS",
    "INR.format": "INR %@",
    "INR.variants": "Indian Rupee",
    "IQD.format": "%@ IQD",
    "IQD.variants": "Iraqi Dinars,Iraqi Dinar,ع.د",
    "IRR.format": "%@ IR",
    "IRR.variants": "Iranian Rial,Iranian Rials,IR",
    "ISK.format": "%@ kr",
    "ISK.variants": "Icelandic krona,Icelandic kronas,Iceland Krona,Iceland Kronas",
    "JMD.format": "%@ JMD",
    "JMD.variants": "Jamaican Dollar,Jamaican Dollars",
    "JOD.format": "%@ JD",
    "JOD.variants": "Jordanian Dinars,Jordanian Dinar,دينار,JD",
    "JPY.format": "¥ %@",
    "JPY.variants": "Japanese Yen,Yen,¥",
    "KES.format": "%@ KSh",
    "KES.variants": "Kenyan Shillings,Kenyan Shilling,KSh",
    "KGS.format": "%@ sом",
    "KGS.variants": "Kyrgyzstani Soms,Kyrgyzstani Som,Soms,Som,sом",
    "KHR.format": "%@ R.",
    "KHR.variants": "Cambodian Riel,Riel,៛,Cambodian Riels,Riels",
    "KMF.format": "%@ FC",
    "KMF.variants": "Comorian Francs,Comorian Franc,FC",
    "KPW.format": "￦ %@",
    "KPW.variants": "North Korean won",
    "KRW.format": "￦ %@",
    "KRW.variants": "South Korean Won,Won",
    "KWD.format": "%@ KD",
    "KWD.variants": "Kuwaiti Dinars,Kuwaiti Dinar,د.ك,KD",
    "KYD.format": "$ %@",
    "KYD.variants": "Cayman Islands Dollars,Cayman Islands Dollar",
    "KZT.format": "%@ T",
    "KZT.variants": "Kazakhstani Tenge,Tenge",
    "LAK.format": "%@ K",
    "LAK.variants": "Lao Kips,Lao Kip,Kips,Kip",
    "LBP.format": "%@ .ل.ل",
    "LBP.variants": "Lebanese Pound,Lebanese Pounds,.ل.ل",
    "LKR.format": "Rs %@",
    "LKR.variants": "Sri Lanka Rupee",
    "LRD.format": "L$ %@",
    "LRD.variants": "Liberian Dollars,Liberian Dollar,L$",
    "LSL.format": "M %@",
    "LSL.variants": "Lesotho maloti,Lesotho loti,loti,Maloti",
    "LTL.format": "%@ Lt",
    "LTL.variants": "Lithuanian Litas,Lithuanian Litai,Litas,Litai,Lt",
    "LVL.format": "%@ Ls",
    "LVL.variants": "Latvian Lats,Lat,Latvian Lati,Lati,Latvian Latu,Latu,Ls",
    "LYD.format": "%@ LD",
    "LYD.variants": "Libyan Dinar,Libyan Dinars,د.ل",
    "MAD.format": "%@ Dh",
    "MAD.variants": "Moroccan Dirham,Moroccan Dirhams,د.م.",
    "MDL.format": "%@ lei",
    "MDL.variants": "Moldovan Leu,Moldovan Lei,Leu",
    "MGA.format": "Ar %@",
    "MGA.variants": "Malagasy ariary,ariary",
    "MKD.format": "%@ den.",
    "MKD.variants": "Macedonian Denar,Macedonian Denari,den.",
    "MMK.format": "K %@",
    "MMK.variants": "Myanmar Kyat,Burmese kyat,kyat",
    "MNT.format": "%@ ₮",
    "MNT.variants": "Mongolian Tugrik,Tugrik,₮",
    "MOP.format": "MOP$ %@",
    "MOP.variants": "Macanese Pataca,Macao Pataca,Macau Pataca,Pataca,Macanese Patacas,Patacas,Macao Patacas,MOP$",
    "MRO.format": "%@ UM",
    "MRO.variants": "Mauritanian ouguiya,ouguiya",
    "MUR.format": "Rs %@",
    "MUR.variants": "Mauritius Rupee,Mauritius Rupees",
    "MVR.format": "Rf %@",
    "MVR.variants": "Maldivian Rufiyaa,Rufiyaa,Rf",
    "MWK.format": "%@ MK",
    "MWK.variants": "Malawian Kwacha,Kwacha",
    "MXN.format": "$ %@",
    "MXN.variants": "Mexican Peso,Mexican Pesos",
    "MYR.format": "RM %@",
    "MYR.variants": "Malaysian Ringgit,Ringgit",
    "MZN.format": "%@ MT",
    "MZN.variants": "Mozambican Metical,Mozambican Meticais,Metical,Meticais",
    "NAD.format": "N$ %@",
    "NAD.variants": "Namibian Dollar,Namibian Dollars,N$",
    "NGN.format": "%@ ₦",
    "NGN.variants": "Nigerian Naira,Naira,₦",
    "NIO.format": "C$ %@",
    "NIO.variants": "Nicaraguan Cordoba,Cordoba,Cordobas,Nicaraguan Cordobas,C$",
    "NOK.format": "%@ kr",
    "NOK.variants": "Norwegian Krone,Norwegian Kroner",
    "NPR.format": "₨ %@",
    "NPR.variants": "Nepalese Rupee,Nepalese Rupees,₨",
    "NZD.format": "$%@ NZD",
    "NZD.variants": "New Zealand Dollar,New Zealand Dollars",
    "OMR.format": "%@ RO",
    "OMR.variants": "Omani Rial,Omani Rials,ر.ع.,RO",
    "PAB.format": "%@ B/.",
    "PAB.variants": "Panamanian Balboa,Balboa,Panamanian Balboas,Balboas,B/.",
    "PEN.format": "%@ S/.",
    "PEN.variants": "Peruvian Nuevo Sol,Nuevo Sol,Peruvian Nuevo Soles,Nuevo Soles,S/.",
    "PGK.format": "%@ K",
    "PGK.variants": "Papua New Guinean Kina,Kina",
    "PHP.format": "%@ ₱",
    "PHP.variants": "Philippine Peso,Philippine Pesos,₱",
    "PKR.format": "Rs %@",
    "PKR.variants": "Pakistan Rupee,Pakistan Rupees",
    "PLN.format": "%@ zł",
    "PLN.variants": "Polish Zloty,Zloty,zł",
    "PYG.format": "%@ ₲",
    "PYG.variants": "Paraguayan Guarani,Guarani,Paraguayan Guaranies,Guaranies,₲",
    "QAR.format": "%@ QR",
    "QAR.variants": "Qatari Rial,Qatari Rials",
    "RON.format": "%@ lei",
    "RON.variants": "Romanian Lei,Romanian Leu",
    "RSD.format": "%@ RSD",
    "RSD.variants": "Serbian Dinar,Serbian Dinars",
    "RUB.format": "%@ ₽",
    "RUB.variants": "russian rouble,russian roubles,ru rouble,ru roubles,rus roubles,rus rouble,russian ruble,russian rubles,rouble,ruble,rubles,roubles,₽",
    "RWF.format": "%@ RF",
    "RWF.variants": "Rwandan franc,Rwandan francs",
    "SAR.format": "%@ SR",
    "SAR.variants": "Saudi Riyal,Saudi Riyals,﷼‎,ر.س",
    "SBD.format": "SI$ %@",
    "SBD.variants": "Solomon Islands Dollar,Solomon Islands Dollars,SI$",
    "SCR.format": "%@ SR",
    "SCR.variants": "Seychelles Rupees,Seychelles Rupee,Seychellois Rupees,Seychellois Rupee",
    "SDG.format": "%@ £Sd",
    "SDG.variants": "Sudanese Pound,Sudanese Pounds,ج.س.‏,£Sd",
    "SEK.format": "%@ kr",
    "SEK.variants": "Swedish Krona,Swedish Kronor",
    "SGD.format": "S$ %@",
    "SGD.variants": "Singapore Dollar,Singapore Dollars,S$",
    "SHP.format": "£%@ SHP",
    "SHP.variants": "St Helena Pounds,St Helena Pound,Saint Helena pound,Saint Helena pounds",
    "SLL.format": "%@ Le",
    "SLL.variants": "Sierra Leonean Leone,Sierra Leonean Leones,Leone,Leones",
    "SOS.format": "%@ So.",
    "SOS.variants": "Somali Shillings,Somali Shilling,Sh.,So.",
    "SRD.format": "$ %@",
    "SRD.variants": "Surinamese Dollar,Surinamese Dollars",
    "SSP.format": "%@ SSP",
    "SSP.variants": "South Sudanese pound,South Sudanese pounds",
    "STD.format": "%@ Db",
    "STD.variants": "São Tomé and Príncipe Dobra,São Tomé and Príncipe Dobras,Dobra,Dobras",
    "SVC.format": "%@ ₡",
    "SVC.variants": "El Salvador Colon,Salvadoran colon,Salvadoran colones",
    "SYP.format": "S£ %@",
    "SYP.variants": "Syrian Pound,Syrian Pounds,S£",
    "SZL.format": "E %@",
    "SZL.variants": "Swazi Lilangeni,Lilangeni,Swazi Emalangeni,Emalangeni",
    "THB.format": "฿ %@",
    "THB.variants": "Thai Baht,Baht,฿",
    "TJS.format": "%@ TJS",
    "TJS.variants": "Tajikistani Somoni,Somoni",
    "TMT.format": "%@ TMT",
    "TMT.variants": "Turkmenistan Manat,Manat",
    "TND.format": "%@ TD",
    "TND.variants": "Tunisian Dinar,Tunisian Dinars,د.ت,TD",
    "TOP.format": "T$ %@",
    "TOP.variants": "Tongan Paʻanga,Paʻanga,T$",
    "TRY.format": "₺%@",
    "TRY.variants": "Turkish Lira,₺",
    "TTD.format": "TT$ %@",
    "TTD.variants": "Trinidad and Tobago Dollar,Trinidad and Tobago Dollars,TT$",
    "TWD.format": "NT$ %@",
    "TWD.variants": "New Taiwan Dollars,New Taiwan Dollar,NT$,NT Dollar, NTD",
    "TZS.format": "%@ TSh",
    "TZS.variants": "Tanzanian Shilling,Tanzanian Shillings,Tanzanian Shillingi,TSh",
    "UAH.format": "%@ UAH",
    "UAH.variants": "Ukrainian Hryvnia,Ukrainian Hryvni,Ukrainian Hryven',Hryvnia,Hryvni,Hryven',₴,grn.",
    "UGX.format": "%@ USh",
    "UGX.variants": "Ugandan Shilling,Ugandan Shillings,USh",
    "USD.format": "$%@",
    "USD.variants": "dollar USA,dollars USA,dollar,USD,dollars,U.S. Dollars,U.S. Dollar,USA Dollars,USA Dollar,$",
    "UYU.format": "$U %@",
    "UYU.variants": "Uruguayan Peso,Uruguayan Pesos,$U",
    "UZS.format": "%@ som",
    "UZS.variants": "Uzbekistani som,som,so'm",
    "VEF.format": "Bs.F. %@",
    "VEF.variants": "Venezuelan Bolívar,Venezuelan Bolivar,Venezuelan Bolívares,Venezuelan Bolivares,bolívar fuerte,bolivar fuerte,bolívares fuertes,Bs.F.",
    "VND.format": "%@ ₫",
    "VND.variants": "Vietnamese Dong,Dong,₫",
    "VUV.format": "%@ VT",
    "VUV.variants": "Vanuatu Vatu,Vatu",
    "WST.format": "WS$ %@",
    "WST.variants": "Samoan Tala,Tala,WS$",
    "XAF.format": "%@ FCFA",
    "XAF.variants": "CFA Franc (Beac),Central African CFA franc,Central African CFA francs,CFA francs,CFA franc,Franc CFA BEAC,FCFA",
    "XCD.format": "EC$ %@",
    "XCD.variants": "East Caribbean Dollar,East Caribbean Dollars,EC$",
    "XOF.format": "%@ CFA",
    "XOF.variants": "West African CFA franc,franc CFA BCEAO,CFA",
    "XPF.format": "%@ F",
    "XPF.variants": "CFP Franc,CFP Francs,franc pacifique,francs pacifique",
    "YER.format": "%@ YER",
    "YER.variants": "Yemeni Rial,Yemeni Rials,﷼",
    "ZAR.format": "R %@",
    "ZAR.variants": "South African Rand,Rand",
    "ZMW.format": "%@ ZMK",
    "ZMW.variants": "Zambian Kwacha,Kwacha,ZMK"
  },
  "Data": {
    "bit.format": "b",
    "bit.symbol": "b",
    "bit.variants": "bit,bits,b",
    "byte.format": "B",
    "byte.symbol": "B",
    "byte.variants": "byte,bytes,B"
  },
  "Dates": {
    "current_time.variants": "time,now",
    "local_time.variants": "local,local timezone,local time zone",
    "today.variants": "today",
    "tomorrow.variants": "tomorrow",
    "yesterday.variants": "yesterday"
  },
  "IECPrefixes": {
    "exbi.prefix": "exbi",
    "exbi.symbol": "Ei",
    "gibi.prefix": "gibi",
    "gibi.symbol": "Gi",
    "kibi.prefix": "kibi",
    "kibi.symbol": "Ki",
    "mebi.prefix": "mebi",
    "mebi.symbol": "Mi",
    "pebi.prefix": "pebi",
    "pebi.symbol": "Pi",
    "tebi.prefix": "tebi",
    "tebi.symbol": "Ti",
    "yobi.prefix": "yobi",
    "yobi.symbol": "Yi",
    "zebi.prefix": "zebi",
    "zebi.symbol": "Zi"
  },
  "Length": {
    "cable.format": "cable",
    "cable.variants": "cable,cables",
    "chain.format": "chain",
    "chain.variants": "chain,chains",
    "foot.format": "ft",
    "foot.variants": "foot,foots,ft,ft.,feet,feets",
    "furlong.format": "furlong",
    "furlong.variants": "furlong,furlongs",
    "inch.format": "″",
    "inch.variants": "inches,inch,″",
    "league.format": "league",
    "league.variants": "league,leagues",
    "meter.format": "m",
    "meter.symbol": "m",
    "meter.variants": "meter,metre,metres,meters,m",
    "mile.format": "mi.",
    "mile.variants": "mile,miles,mi,mi.",
    "nautical_mile.format": "n.m.",
    "nautical_mile.variants": "nmi,nautical mile,nautical miles,n.m.",
    "point.format": "pt",
    "point.variants": "point,points,pt,pt.",
    "yard.format": "yd",
    "yard.variants": "yard,yards,yd,yd."
  },
  "Numbers": {
    "binary.variants": "binary,bin",
    "decimal.variants": "decimal,dec",
    "hex.variants": "hex",
    "octal.variants": "octal",
    "scientific.variants": "scientific, sci, exp, exponent, exponential"
  },
  "Operations": {
    "assignment.variants": "equal,is",
    "avg.variants": "average,avg",
    "cbrt.variants": "cbrt,cubic root,cube root,cubed root",
    "conversion.variants": "in,into,as,to",
    "divide.variants": "divide,divide by,divided by",
    "minus.variants": "minus,without,subtract",
    "multiply.variants": "times,multiplied by,multiply,mul,mult",
    "plus.variants": "with,plus,and",
    "prev.variants": "prev",
    "sqrt.variants": "sqrt,square root",
    "sum.variants": "sum,total"
  },
  "Percent": {
    "as_a_percent_of.variants": "as a % of,as a percent of",
    "as_a_percent_off.variants": "as a % off,as a percent off,as a % decrease of,as a percent decrease of",
    "as_a_percent_on.variants": "as a % on,as a percent on,as a % increase of,as a percent increase of",
    "percent.format": "%%",
    "percent.variants": "%,percent,percents,pct,pct.",
    "percent_of.variants": "from,of",
    "percent_of_what_is.variants": "of what is",
    "percent_off.variants": "off",
    "percent_off_what_is.variants": "off what is",
    "percent_on.variants": "on",
    "percent_on_what_is.variants": "on what is"
  },
  "SIPrefixes": {
    "atto.prefix": "atto",
    "atto.symbol": "a",
    "centi.prefix": "centi",
    "centi.symbol": "c",
    "deca.prefix": "deca",
    "deca.symbol": "da",
    "deci.prefix": "deci",
    "deci.symbol": "d",
    "exa.prefix": "exa",
    "exa.symbol": "E",
    "femto.prefix": "femto",
    "femto.symbol": "f",
    "giga.prefix": "giga",
    "giga.symbol": "G",
    "hecto.prefix": "hecto",
    "hecto.symbol": "h",
    "kilo.prefix": "kilo",
    "kilo.symbol": "k",
    "mega.prefix": "mega",
    "mega.symbol": "M",
    "micro.prefix": "micro",
    "micro.symbol": "µ",
    "milli.prefix": "milli",
    "milli.symbol": "m",
    "nano.prefix": "nano",
    "nano.symbol": "n",
    "peta.prefix": "peta",
    "peta.symbol": "P",
    "pico.prefix": "pico",
    "pico.symbol": "p",
    "tera.prefix": "tera",
    "tera.symbol": "T",
    "yocto.prefix": "yocto",
    "yocto.symbol": "y",
    "yotta.prefix": "yotta",
    "yotta.symbol": "Y",
    "zepto.prefix": "zepto",
    "zepto.symbol": "z",
    "zetta.prefix": "zetta",
    "zetta.symbol": "Z"
  },
  "Samples": {
    "sample.welcome": "# Summarum\n8 / (45 - 20%)\n5 inches in cm\n$9 in euro\n100 km/h in mph"
  },
  "Scales": {
    "billion.variants": "billion,Billion,milliard,Milliard,billions,Billions,milliards,Milliards",
    "million.variants": "million,Million,millions,Millions,M",
    "thousand.variants": "thousand,Thousand,thousands,Thousands,th.,th,k"
  },
  "Temperature": {
    "celsius.format": "°C",
    "celsius.variants": "celsius,C,°C",
    "fahrenheit.format": "°F",
    "fahrenheit.variants": "fahrenheit,fahrenheits,F,°F",
    "kelvin.format": "K",
    "kelvin.variants": "kelvin,kelvins,K"
  },
  "Time": {
    "day.format": "day",
    "day.variants": "day,days,d",
    "hour.format": "h",
    "hour.variants": "h,hr,hour,hours",
    "minute.format": "min",
    "minute.variants": "min,minute,minutes",
    "month.format": "mon.",
    "month.variants": "month,monthes,months,mon,mon.",
    "second.format": "s",
    "second.symbol": "s",
    "second.variants": "s,sec,second,seconds",
    "week.format": "w",
    "week.variants": "week,w,weeks",
    "year.format": "yr",
    "year.variants": "y,yr,year,years"
  },
  "Volume": {
    "cbcm.variants": "cc,ccm",
    "cbinch.variants": "c.i.,CI,cui,cu inch",
    "cup.format": "cup",
    "cup.variants": "cup,cups",
    "gallon.format": "gal.",
    "gallon.variants": "gallon,gallons,gal.,gal",
    "litre.format": "L",
    "litre.symbol": "l",
    "litre.variants": "litre,litres,liter,liters,l,L",
    "pint.format": "pint",
    "pint.variants": "pint,pints",
    "quart.format": "qt.",
    "quart.variants": "quart,quarts,qt.,qt",
    "tablespoon.format": "tbsp.",
    "tablespoon.variants": "tablespoon,tablespoons,table spoon,table spoons,tbsp.,tbsp,T.",
    "teaspoon.format": "tsp.",
    "teaspoon.variants": "teaspoon,teaspoons,tea spoon,tea spoons,t.,tsp.,tsp",
    "volume.format": "%@³",
    "volume.templates": "cu %@,cubic %@,cb %@,cb%@,%@³,%@ ³,%@ 3"
  },
  "Weight": {
    "carat.format": "ct",
    "carat.variants": "carat,carats,CD,ct",
    "centner.format": "centner",
    "centner.variants": "centner,quintal,centners,quintals",
    "gram.format": "g",
    "gram.symbol": "g",
    "gram.variants": "gram,gramme,grams,grammes,g",
    "ounce.format": "oz",
    "ounce.variants": "ounce,ounces,oz",
    "pound.format": "lb",
    "pound.variants": "pound,pounds,lb,lbm",
    "stone.format": "st",
    "stone.variants": "stone,stones,st",
    "tonne.format": "t",
    "tonne.symbol": "t",
    "tonne.variants": "tonne,tonnes,t,metric ton"
  }
};

export const RU: VocabLocale = {
  "Angle": {
    "degree.format": "°,градус,градусов,градусы",
    "degree.variants": "°,градус,градусов,градусах,градуса,град,град.",
    "radian.format": "рад",
    "radian.variants": "радиан,рад,радианах"
  },
  "Area": {
    "acre.format": "акр",
    "acre.variants": "акр,акров,акра,акрах",
    "are.format": "а",
    "are.variants": "ар,ара,арах,аров",
    "hectare.format": "га",
    "hectare.variants": "гектар,гектаров,гектара,гектарах,га",
    "ping.format": "пинг",
    "ping.variants": "пинг,пинги"
  },
  "Css": {
    "pixel.variants": "пиксел,пиксела,пикселу,пикселом,пикселе,пиксель,пикселя,пикселю,пекселем,пиксели,пикселей,пикселям,пикселями,пикселях,пикс."
  },
  "Currency": {
    "AED.variants": "Дирхам ОАЭ,Дирхамы ОАЭ,Дирхам",
    "AFN.variants": "Афгани",
    "ALL.format": "%@ Lek",
    "ALL.variants": "Лек,Албанский лек",
    "AMD.format": "%@ Драм",
    "AMD.variants": "Драм,Драмов,Драмы,Армянский драм,Армянские драмы,Армянских драмов",
    "ANG.format": "%@ ƒ",
    "ANG.variants": "Гульден,Гульденов,Гульдены,Гульденах",
    "AOA.variants": "Кванза,Кванзы,Ангольская кванза,Ангольские кванзы,кванзах",
    "ARS.variants": "Аргентинское песо,Аргентинских песо",
    "AUD.variants": "Австралийский доллар,Австралийских долларов,Австралийских долларах",
    "AWG.format": "%@ ƒ",
    "AWG.variants": "Арубанский флорин,Арубанских флоринов,Арубанских флоринах",
    "AZN.format": "%@ ман.",
    "AZN.variants": "Азербайджанский манат,Азербайджанских манат,Азербайджанских манатах,манат,манатах,man.,ман.",
    "BAM.variants": "Конвертируемая марка,Конвертируемых марок,Конвертируемых марках",
    "BBD.variants": "Барбадосский доллар,Барбадосские доллары,Барбадосских долларов,Барбадосских долларах",
    "BDT.variants": "Така,Таков,Таках,Таки",
    "BGN.format": "%@ лв",
    "BGN.variants": "Болгарский лев,Болгарских левов,Болгарские левы,Болгарских левах,Лев,Левов,Левах,Болг. левов,Болг. лев,Болг. левах",
    "BHD.variants": "Бахрейнский динар,Бахрейнских динаров,Бахрейнских динарах,Динар,Динарах,Динаров",
    "BIF.variants": "Бурундийский франк,Бурундийских франков,Бурундийские франки,Бурундийских франках",
    "BMD.format": "%@ $",
    "BMD.variants": "Бермудский доллар,Бермудских долларов,Бермудских долларах,Бермудские доллары",
    "BND.format": "%@ B$",
    "BND.variants": "Брунейский доллар,Брунейских долларов,Брунейских долларах,Брунейские доллары",
    "BOB.format": "%@ Bs",
    "BOB.variants": "Боливиано",
    "BRL.format": "%@ R$",
    "BRL.variants": "Бразильский реал,Бразильских реалов,Бразильских реалах,Бразильские реалы,Реал,Реалов,Реалах",
    "BSD.format": "%@ B$",
    "BSD.variants": "Багамский доллар,Багамских долларов,Багамских долларах,Багамские доллары",
    "BTC.variants": "Bitcoins,Bitcoin,Биткоин,Биткойн,Биткоинов,Биткойнов,Биткоинах,Биткойнах,Биткоины,Биткойны",
    "BTN.format": "%@ Nu",
    "BTN.variants": "Нгултрум,Нгултрумах,Нгултрумов",
    "BWP.variants": "Пула,Пул,Пулах",
    "BYN.format": "%@ BYN",
    "BYN.variants": "белорусский рубль,белорусских рублей,белорусских рублях,белорусских рубля,бел. рублях,бел. рубль,бел. рублей,бел. рубля,бел руб,бел руб.,бел. руб.,Br",
    "BZD.format": "%@ BZ$",
    "BZD.variants": "Белизский доллар,Белизских долларах,Белизских долларов,Белизские доллары",
    "CAD.format": "%@ CA$",
    "CAD.variants": "Канадский доллар,Канадских долларов,Канадских долларах,Канадские доллары",
    "CDF.variants": "Конголезский франк,Конголезских франков,Конголезских франках,Конголезские франки",
    "CHF.format": "%@ SFr",
    "CHF.variants": "Швейцарский франк,Швейцарских франков,Швейцарских франках,Швейцарские франки,Франк,Франков,Франках",
    "CLP.variants": "Чилийское песо,Чилийских песо",
    "CNY.variants": "Юань,Юаней,Юаня,Юанях",
    "COP.variants": "Колумбийское песо,Колумбийские песо,Колумбийских песо",
    "CRC.format": "%@ C",
    "CRC.variants": "Костариканский колон,Костариканских колонах,Костариканских колон,Колон,Колонах",
    "CUP.format": "%@ $MN",
    "CUP.variants": "Кубинское песо,Кубинский песо,Кубинских песо",
    "CVE.variants": "Эскудо Кабо-Верде,Эскудо",
    "CZK.variants": "Чешская крона,Чешские кроны,Чешских крон,Чешских кронах",
    "DJF.variants": "Франк Джибути,Франков Джибути,Франках Джибути",
    "DKK.format": "%@ kr",
    "DKK.variants": "Датские кроны,Датская Крона,Датских кронах,Датских крон",
    "DOP.format": "%@ RD$",
    "DOP.variants": "Доминиканское песо,Золотой песо,Доминиканских песо",
    "DZD.variants": "Алжирские динары,Алжирский динар,Алжирских динар,Алжирских динарах",
    "EGP.format": "%@ EGP",
    "EGP.variants": "Египетские фунты,Египетский Фунт,Египетских фунтов,Египетских Фунтах",
    "ERN.variants": "Накфа,Накфах,Накф",
    "ETB.variants": "Эфиопский быр,Быр,Быров,Бырах",
    "EUR.format": "%@ €",
    "EUR.variants": "Евро",
    "FJD.format": "%@ FJ$",
    "FJD.variants": "Доллар Фиджи,Долларах Фиджи,Долларов Фиджи",
    "FKP.format": "%@ £",
    "FKP.variants": "Фунт Фолклендских островов,Фолклендский фунт,Фолклендских фунтов,Фолклендских фунтах",
    "GBP.format": "%@ £",
    "GBP.variants": "Фунт стерлингов,Фунтов стерлингов,Фунтах стерлингов,Британский фунт,Британских фунтов,Британских фунтах,стерлинг,стерлинга,стерлингов,стерлинги,стерлингам,стерлингами,стерлингах",
    "GEL.variants": "Грузинский лари,Лари",
    "GHS.format": "%@ GH₵",
    "GHS.variants": "Ганский седи,Седи",
    "GIP.variants": "Гибралтарский фунт,Гибралтарских фунтов,Гибралтарских фунтах",
    "GMD.variants": "Даласи,Гамбийский даласи",
    "GNF.format": "%@ GFr",
    "GNF.variants": "Гвинейский франк,Гвинейских франках,Гвинейских франков",
    "GTQ.variants": "Гватемальский кетсаль,Кетсаль,Кетцаль,Кетсалей,Кетсалях",
    "GYD.format": "%@ GY$",
    "GYD.variants": "Гайанские доллары,Гайанский доллар,Гайанских долларах,Гайанских долларов",
    "HKD.format": "%@ HK$",
    "HKD.variants": "Гонконгские доллары,Гонконгский доллар,Гонконгских долларов,Гонконгских долларах",
    "HNL.format": "%@ L",
    "HNL.variants": "Гондурасская лемпира,Лемпира,Лемпирах,Лемпир",
    "HRK.variants": "Хорватская куна,Хорватских кунах,Куна,Кунах",
    "HTG.variants": "Гурд,Гаитянский гурд,Гурдов,Гурдах",
    "HUF.format": "%@ ft",
    "HUF.variants": "Форинт,Форинтов,Форинтах,Венгерский форинт",
    "IDR.format": "%@ Rp",
    "IDR.variants": "Индонезийские рупии,Индонезийская рупия,Индонезийских рупиях,Индонезийских рупий",
    "ILS.variants": "Новый израильский шекель,Новый шекель,Новых шекелей,новых шекелях",
    "INR.format": "%@ Re.",
    "INR.variants": "Индийские рупии,Индийская рупия,Индийских рупиях,Индийских рупий",
    "IQD.format": "%@ ID",
    "IQD.variants": "Иракские Динары,Иракский Динар,Иракских Динарах,Иракских Динаров",
    "IRR.variants": "Иранские риалы,Иранский риал,Иранских риалов,Иранских риалах,Риал,Риалах,Риалов",
    "ISK.variants": "Исландские кроны,Исландская крона,Исландских крон,Исландских кронах",
    "JMD.variants": "Ямайские доллары,Ямайский доллар,Ямайских долларов,Ямайских долларах",
    "JOD.variants": "Иорданские динары,Иорданский динар,Иорданских динаров,Иорданских динарах",
    "JPY.format": "%@ ¥",
    "JPY.variants": "японская иена,иена,иен,иены,йен,йены,йена,японская йена",
    "KES.variants": "Кенийские шиллинги,Кенийский шиллинг,Кенийских шиллингов,Кенийских шиллингах",
    "KGS.format": "%@ сом",
    "KGS.variants": "Кыргызский сом,Сом,Сомов,Сомах,Сома",
    "KHR.variants": "Камбоджийский Риель,Риель,Риелей,Риелях",
    "KMF.variants": "Франк Комор,Коморский франк,Коморских франках",
    "KPW.format": "%@ ￦",
    "KPW.variants": "Северокорейская вона,Вона КНДР,Северокорейских вон,Северокорейских вонах",
    "KRW.format": "%@ ￦",
    "KRW.variants": "Южнокорейская вона,Вона,вон,вонах,Южнокорейских вонах",
    "KWD.variants": "Кувейтский динар,Кувейтских динарах,Кувейтских динаров",
    "KYD.format": "%@ $",
    "KYD.variants": "Доллар Островов Кайман,Доллар Каймановых островов,Долларах Каймановых островов",
    "KZT.variants": "Казахстанский Тенге,Тенге",
    "LAK.variants": "Лаосский кип,Кип,Кипах",
    "LBP.variants": "Ливанские Фунты,Ливанский Фунт,Ливанских фунтах",
    "LKR.format": "%@ Rs",
    "LKR.variants": "Шри-Ланкийская рупия,Шри-Ланкийских рупий,Шри-Ланкийских рупиях",
    "LRD.format": "%@ L$",
    "LRD.variants": "Либерийские Доллары,Либерийский доллар,Либерийских долларах",
    "LSL.format": "%@ M",
    "LSL.variants": "Лоти,Лоти Лесото,Малоти",
    "LTL.variants": "Литовский лит,Лит,Литах",
    "LVL.variants": "Латвийский лат,Лат,Латах",
    "LYD.variants": "Ливийские динары,Ливийский динар,Ливийских динарах,Ливийских динар",
    "MAD.variants": "Марокканский дирхам,Дирхам,Дирхамов,Дирхамах",
    "MDL.variants": "Молдавский лей,Молдавских леев,Молдавских леях,Лей,молд. лей,молд. леях,молд. леев",
    "MGA.format": "%@ Ar.",
    "MGA.variants": "Малагасийский ариари,Ариари",
    "MKD.format": "%@ ден.",
    "MKD.variants": "Македонский денар,Денар,Денарах",
    "MMK.format": "%@ K",
    "MMK.variants": "Кьят,Кьятах",
    "MNT.variants": "Монгольский тугрик,Тугрик,Тугриков,Тугриках",
    "MOP.format": "%@ $",
    "MOP.variants": "Патака Макао,Патака,Патак,Патаках",
    "MRO.variants": "Мавританская угия,Угия,Угий,Угиях",
    "MUR.format": "%@ Rs",
    "MUR.variants": "Маврикийская рупия,Маврикийских рупий,Маврикийских рупиях",
    "MVR.format": "%@ Rf",
    "MVR.variants": "Мальдивская руфия,Руфия,Руфий,Руфиях",
    "MWK.variants": "Малавийская квача,Малавийских квач,Малавийских квачах,Квача,Квачах",
    "MXN.format": "%@ $",
    "MXN.variants": "Мексиканских песо,Мексиканское песо",
    "MYR.format": "%@ RM",
    "MYR.variants": "Малайзийский ринггит,Ринггит,Ринггитах",
    "MZN.variants": "Мозамбикский метикал,Метикал,Метикалов,Метикалах",
    "NAD.format": "%@ N$",
    "NAD.variants": "Доллар Намибии,Намибийский доллар,Намибийских долларов,Намибийских долларах",
    "NGN.variants": "Найра,Нигерийская найра,Найр,Найрах",
    "NIO.format": "%@ C$",
    "NIO.variants": "Никарагуанская кордоба,Золотая Кордоба,Кордоба,Кордоб,Кордобах",
    "NOK.variants": "Крона,Норвежская крона,Норвежских крон,Норвежских кронах,Крон,Кронах",
    "NPR.format": "%@ ₨",
    "NPR.variants": "Непальские рупии,Непальская рупия,Непальских рупий,Непальских рупиях",
    "NZD.variants": "Новозеландские доллары,Новозеландский доллар,Новозеландских долларах,Новозеландских долларов",
    "OMR.variants": "Оманские риалы,Оманский риал,Оманских риалов,Оманских риала",
    "PAB.format": "%@ B",
    "PAB.variants": "Панамский бальбоа,Бальбоа",
    "PEN.variants": "Новый соль,Перуанский Новый соль,Солей,Новых солей,Новых солях,Солях",
    "PGK.variants": "Кина",
    "PHP.format": "%@ PhP",
    "PHP.variants": "Филиппинское песо,Филиппинских песо",
    "PKR.format": "%@ Rs",
    "PKR.variants": "Пакистанских рупий,Пакистанских рупиях,Пакистанская рупия",
    "PLN.variants": "Польский злотый,Злотый,Злотых,Злотые",
    "PYG.format": "%@ G",
    "PYG.variants": "Парагвайский гуарани,Гуарани",
    "QAR.variants": "Катарские риалы,Катарский риал,Катарских риалах",
    "RON.variants": "Румынский лей,Новый румынский лей,Лей,Леев,Леях,Румынских леев,Румынских леях",
    "RSD.format": "%@ дин.",
    "RSD.variants": "Сербские динары,Сербский динар,Сербских динарах,Сербских динар",
    "RUB.variants": "Российский рубль,Российских рублей,Российских рублях,Российские рубли,Рос. рубль,Рос. рублей,Рос. рублях,Рос. руб.,росс. руб.,росс руб,рос руб.,рубль,руб,руб.,₽,рубля,рублю,рублем,рубле,рубли,рублей,рублями,рублях",
    "RWF.variants": "Франк Руанды,Руандийский франк,Руандийских франков,Руандийских франках",
    "SAR.variants": "Саудовский риял,Риял Саудовской аравии,Риял,Риялов,Риялах,Саудовских риялах",
    "SBD.format": "%@ SI$",
    "SBD.variants": "Доллар Соломоновых Островов,Долларов Соломоновых Островов,Долларах Соломоновых Островов",
    "SCR.variants": "Сейшельские рупии,Сейшельская рупия,Сейшельских рупиях,Сейшельских рупий",
    "SDG.format": "%@ £",
    "SDG.variants": "Суданские фунты,Суданский фунт,Суданских фунтов,Суданских фунтах",
    "SEK.variants": "Шведские кроны,Шведская крона,Шведских крон,Шведских кронах",
    "SGD.format": "%@ S$",
    "SGD.variants": "Сингапурские доллары,Сингапурский доллар,Сингапурских долларов,Сингапурских долларах",
    "SHP.format": "%@ £",
    "SHP.variants": "Фунт Святой Елены,Фунтов Святой Елены,Фунтах Святой Елены",
    "SLL.variants": "Леоне",
    "SOS.variants": "Сомалийские шиллингы,Сомалийский шиллинг,Шиллинг,Шиллингов,Шиллингах,Сомалийских шиллингах",
    "SRD.format": "%@ $",
    "SRD.variants": "Суринамский доллар,Суринамских долларов,Суринамских долларах",
    "SSP.variants": "Южносуданский фунт,Южно-суданский фунт,Южносуданских фунтов,Южносуданских фунтах",
    "STD.variants": "Добра,Добр,Добрах",
    "SVC.format": "%@ C",
    "SVC.variants": "Сальвадорский колон,Колонов,Колон,Колонах",
    "SYP.format": "%@ S£",
    "SYP.variants": "Сирийские фунты,Сирийский фунт,Сирийских фунтов,Сирийских фунтах",
    "SZL.format": "%@ E",
    "SZL.variants": "Свазилендский лилангени,Эмалангени,Лилангени",
    "THB.format": "%@ B",
    "THB.variants": "Тайский бат,Бат,Батов,Батах",
    "TJS.format": "%@ смн.",
    "TJS.variants": "Таджикский сомони,Сомони",
    "TMT.variants": "Туркменский манат,Новый туркменский манат,Манат,Манатов,Туркменских манатов,Маната,Туркменских маната",
    "TND.variants": "Тунисские Динары,Тунисский Динар,Тунисских Динаров,Тунисских Динарах",
    "TOP.format": "%@ T$",
    "TOP.variants": "Тонганская паанга,Паанга,Паангах",
    "TRY.variants": "Турецкая лира,Турецких лир,Турецких лирах,Турецкие лиры",
    "TTD.format": "%@ TT$",
    "TTD.variants": "Доллар Тринидада и Тобаго,Доллар,Долларов Тринидада и Тобаго,Долларах Тринидада и Тобаго",
    "TWD.format": "%@ NT$",
    "TWD.variants": "Новые тайваньские доллары,Новый тайваньский доллар,Новых тайваньских долларах,Новых тайваньских долларов",
    "TZS.variants": "Танзанийские шиллинги,Танзанийский шиллинг,Танзанийских шиллингов,Танзанийских шиллингах",
    "UAH.format": "%@ грн.",
    "UAH.variants": "Украинские гривны,Украинская гривна,Гривна,Гривнах,Гривен,грн.",
    "UGX.variants": "Угандийские шиллинги,Угандийский шиллинг,Угандийских шиллингов,Угандийских шиллингах",
    "USD.format": "%@ $",
    "USD.variants": "Доллары США,Доллар США,Доллар Соединенных Штатов Америки,USD,ам. доллар,амер. доллар,долларов сша,долларах сша,доллары сша,доллар,доллара,долларом,доллары,долларов,долларами,долларах,$",
    "UYU.format": "%@ $U",
    "UYU.variants": "Уругвайское песо,Уругвайских песо",
    "UZS.format": "%@ so’m",
    "UZS.variants": "Узбекский сум,Сум,Сумов,Сумах,Узбекских сумах,Узбекских сумов",
    "VEF.format": "%@ BsF",
    "VEF.variants": "Венесуэльские боливары,Венесуэльский Боливар,Боливар фуэрте,Венесуэльских боливаров,Венесуэльских боливарах,Боливарах фуэрте",
    "VND.format": "%@ dd",
    "VND.variants": "Вьетнамский донг,Донг,Донгов,Донгах",
    "VUV.format": "%@ Vt",
    "VUV.variants": "Вануатский вату,Вату",
    "WST.format": "%@ WS$",
    "WST.variants": "Самоанская тала,Тала,Тал,Талах",
    "XAF.format": "%@ BEAC",
    "XAF.variants": "Франк КФА BEAC,Франк КФА,Франков КФА,Франках КФА",
    "XCD.format": "%@ EC$",
    "XCD.variants": "Восточно-карибские доллары,Восточно-карибский доллар,Восточно-карибских долларов,Восточно-карибских долларах",
    "XOF.format": "%@ BCEAO",
    "XOF.variants": "Франк КФА BCEAO,Франк Африканского финансового сообщества,BCEAO",
    "XPF.variants": "Французский тихоокеанский франк,Франк КФП,Франков КФП,Франках КФП",
    "YER.format": "%@ YR",
    "YER.variants": "Йеменские риалы,Йеменский риал,Йеменских риалов,Йеменских риалах",
    "ZAR.format": "%@ R",
    "ZAR.variants": "Южноафриканский рэнд,Южноафриканский ранд,Ранд,Рэнд,Рэндов,Рэндах,рандов,Рандах",
    "ZMW.format": "%@ K",
    "ZMW.variants": "Замбийская квача,Квача,Квач,Квачах"
  },
  "Data": {
    "bit.format": "бит",
    "bit.symbol": "бит",
    "bit.variants": "бит,битов,битах,битам,биты",
    "byte.format": "Б",
    "byte.symbol": "Б",
    "byte.variants": "байт,байтов,байтам,байтах,Б,байты"
  },
  "Dates": {
    "current_time.variants": "время,сейчас,time,now",
    "local_time.variants": "local,local timezone,local time zone,местное время,локальное время,локально",
    "today.variants": "сегодня",
    "tomorrow.variants": "завтра",
    "yesterday.variants": "вчера"
  },
  "IECPrefixes": {
    "exbi.prefix": "эксби",
    "exbi.symbol": "Эи",
    "gibi.prefix": "гиби",
    "gibi.symbol": "Ги",
    "kibi.prefix": "киби",
    "kibi.symbol": "Ки",
    "mebi.prefix": "меби",
    "mebi.symbol": "Ми",
    "pebi.prefix": "пеби",
    "pebi.symbol": "Пи",
    "tebi.prefix": "теби",
    "tebi.symbol": "Ти",
    "yobi.prefix": "йоби",
    "yobi.symbol": "Йи",
    "zebi.prefix": "зеби",
    "zebi.symbol": "Зи"
  },
  "Length": {
    "cable.format": "кабельт",
    "cable.variants": "кабельт,кабельтов,кабельтах,кабельта",
    "chain.format": "чейн",
    "chain.variants": "чейн,чейнов,чейнах,чейна",
    "foot.format": "фут",
    "foot.variants": "фут,футов,футах,фута",
    "furlong.format": "фарлонг",
    "furlong.variants": "фарлонг,фарлонгов,фарлонгах,фарлонга",
    "inch.format": "дюйм",
    "inch.variants": "дюйм,дюймов,дюймах,дюйма",
    "league.format": "лига",
    "league.variants": "лига,лиги,лигах",
    "meter.format": "м",
    "meter.symbol": "м",
    "meter.variants": "метров,метрах,метр,метра,м",
    "mile.format": "миля",
    "mile.variants": "миля,миль,милях,мили",
    "nautical_mile.format": "морская миля",
    "nautical_mile.variants": "морская миля,морских миль,морских милях,морских мили",
    "point.format": "точка",
    "point.variants": "точка,точек,точках,точки",
    "yard.format": "ярд",
    "yard.variants": "ярд,ярдов,ярдах,ярда"
  },
  "Operations": {
    "assignment.variants": "равно,соответствует",
    "avg.variants": "среднее,средн.,средн",
    "cbrt.variants": "кубический корень,куб корень,куб. корень",
    "conversion.variants": "в,как",
    "divide.variants": "разделить,разделить на,делим,делим на",
    "minus.variants": "минус,без",
    "multiply.variants": "раз по,раз,умножить,по",
    "plus.variants": "и,плюс,вместе с",
    "prev.variants": "пред.,пред",
    "sqrt.variants": "квадратный корень,кв корень,кв. корень",
    "sum.variants": "всего,сумма,итог,итого"
  },
  "Percent": {
    "as_a_percent_of.variants": "как процент от,как процент",
    "as_a_percent_off.variants": "как процентное уменьшение от,как процентное уменьшение для,как процентное уменьшение из",
    "as_a_percent_on.variants": "как процентная добавка к,как процентное увеличение для,как процентное увеличение к",
    "percent.variants": "процент,процента,проценту,процентом,проценте,проценты,процентов,процентам,процентами,процентах,проц,проц.",
    "percent_of.variants": "от,из",
    "percent_of_what_is.variants": "чего является,чего есть,от чего является,от чего есть,от чего,чего",
    "percent_off.variants": "скидка от,снятие из,снятие от,снятие ото,уменьшение из,уменьшение для,уменьшение к",
    "percent_off_what_is.variants": "уменьшение от чего,снятие от чего,уменьшение чего,снятие чего",
    "percent_on.variants": "добавка к,прибавка к,увеличение к,увеличение для",
    "percent_on_what_is.variants": "увеличение чего,увеличение от чего,добавление к чему"
  },
  "SIPrefixes": {
    "atto.prefix": "атто",
    "atto.symbol": "а",
    "centi.prefix": "санти",
    "centi.symbol": "с",
    "deca.prefix": "дека",
    "deca.symbol": "да",
    "deci.prefix": "деци",
    "deci.symbol": "д",
    "exa.prefix": "экса",
    "exa.symbol": "Э",
    "femto.prefix": "фемто",
    "femto.symbol": "ф",
    "giga.prefix": "гига",
    "giga.symbol": "Г",
    "hecto.prefix": "гекто",
    "hecto.symbol": "ч",
    "kilo.prefix": "кило",
    "kilo.symbol": "к",
    "mega.prefix": "мега",
    "mega.symbol": "М",
    "micro.prefix": "микро",
    "micro.symbol": "мк",
    "milli.prefix": "милли",
    "milli.symbol": "м",
    "nano.prefix": "нано",
    "nano.symbol": "н",
    "peta.prefix": "пета",
    "peta.symbol": "П",
    "pico.prefix": "пико",
    "pico.symbol": "п",
    "tera.prefix": "тера",
    "tera.symbol": "Т",
    "yocto.prefix": "иокто",
    "yocto.symbol": "и",
    "yotta.prefix": "иотта",
    "yotta.symbol": "И",
    "zepto.prefix": "зепто",
    "zepto.symbol": "з",
    "zetta.prefix": "зетта",
    "zetta.symbol": "З"
  },
  "Samples": {
    "sample.welcome": "# Summarum\n8 / (45 - 20%)\n5 дюймов в см\n$9 в евро\n100 км/ч в милях"
  },
  "Scales": {
    "billion.variants": "миллиард,миллиардов,миллиарда,млрд,млрд.",
    "million.variants": "миллион,мил.,мил,милл.,милл,миллиона,миллионов,М,млн,млн.",
    "thousand.variants": "тысяч,тысячь,тысячи,тысяча,тыс.,тыс,т,т."
  },
  "Temperature": {
    "celsius.variants": "цельсий,цельсия,цельсиев,цельсиях,цельсиями,градусов цельсия",
    "fahrenheit.variants": "градус фаренгейта,градуса фаренгейта,градусу фаренгейта,градусом фаренгейта,градусы фаренгейта,градусов фаренгейта,градусам фаренгейта,градусами фаренгейта,градусах фаренгейта",
    "kelvin.variants": "кельвин,градус кельвина,градуса кельвина,градусов кельвина,кельвинов,кельвина,кельвине,кельвинах"
  },
  "Time": {
    "day.format": "д",
    "day.variants": "день,дня,дней,днях,д",
    "hour.format": "ч",
    "hour.variants": "час,часа,часов,часах",
    "minute.format": "мин",
    "minute.variants": "мин,мин.,минута,минуты,минут,минутах",
    "month.format": "мес.",
    "month.variants": "месяц,месяца,месяцев,месяцах,мес,мес.",
    "second.format": "с",
    "second.symbol": "с",
    "second.variants": "сек,секунда,секунды,секунд,секундах,сек.",
    "week.format": "нед.",
    "week.variants": "неделя,недели,недель,неделях,нед.,нед",
    "year.format": "г",
    "year.variants": "год,года,лет,годах"
  },
  "Volume": {
    "cbcm.variants": "см³",
    "cbinch.variants": "дюйм³",
    "cup.format": "чаш.",
    "cup.variants": "чашка,чашек,чашках,чашку,чашкам,чаш.,чашк,чашк.,чаш,чашки",
    "gallon.format": "гал.",
    "gallon.variants": "галлон,гал.,гал,галлона,галлонов,галлонах,галлоне",
    "litre.format": "л",
    "litre.symbol": "л",
    "litre.variants": "литр,литров,литрах,литра,л",
    "pint.format": "пинт.",
    "pint.variants": "пинт,пинта,пинтах",
    "quart.format": "кварт.",
    "quart.variants": "кварта,четверть,кварт.,кварт,квартах,кварте",
    "tablespoon.format": "ст. л.",
    "tablespoon.variants": "ст. л.,ст. ложка,столовая ложка,столовой ложки,столовой ложке,столовых ложек,столовые ложки,столовыми ложками,столовых ложках,ст.л.",
    "teaspoon.format": "ч. л.",
    "teaspoon.variants": "ч. л.,ч.л.,чайная ложка,ч. ложка,ч. ложках,ч. ложки,ч. ложками,чайных ложки,чайных ложках,чайной ложке,чайные ложки",
    "volume.templates": "cu %@,cubic %@,cb %@,cb%@,%@³,%@ ³,куб. %@,кубический %@"
  },
  "Weight": {
    "carat.format": "кар",
    "carat.variants": "карата,карат,каратах,каратов,кар",
    "centner.format": "ц",
    "centner.variants": "центнер,центнеров,центнерах,центнера",
    "gram.format": "г",
    "gram.symbol": "г",
    "gram.variants": "грамм,граммов,грамма,граммах",
    "ounce.format": "унция",
    "ounce.variants": "унция,унциях,унции",
    "pound.format": "фунт",
    "pound.variants": "фунт,фунтов,фунтах,фунта",
    "stone.format": "стоун",
    "stone.variants": "стоун,стоунах,стоуна,стоунов",
    "tonne.format": "т",
    "tonne.symbol": "т",
    "tonne.variants": "тонны,тонна,тонн,тоннах"
  }
};
